reate table CUSTOMERS
(
    UUID      CHARACTER VARYING(36) not null
        primary key,
    FIRSTNAME CHARACTER VARYING(255),
    LASTNAME  CHARACTER VARYING(255),
    BIRTHDAY  DATE,
    ADDRESS   CHARACTER VARYING(255)
);

create table CUSTOMERS_BAK
(
    FIRSTNAME CHARACTER VARYING(255),
    LASTNAME  CHARACTER VARYING(255),
    BIRTHDAY  DATE,
    ADDRESS   CHARACTER VARYING(255)
);

create table EMPLOYEES
(
    UUID      CHARACTER VARYING(36) not null
        primary key,
    FIRSTNAME CHARACTER VARYING(255),
    LASTNAME  CHARACTER VARYING(255),
    BIRTHDAY  DATE,
    ADDRESS   CHARACTER VARYING(255)
);

create table EMPLOYEES_BAK
(
    BIRTHDAY  DATE,
    FIRSTNAME CHARACTER VARYING(255),
    LASTNAME  CHARACTER VARYING(255),
    ADDRESS   CHARACTER VARYING(255)
);
